[package]
name = "agc017"
version = "0.1.0"
authors = ["Keigo Oka <ogiekako@gmail.com>"]

[dependencies]

[[bin]]
name="a"
path="src/a.rs"

[[bin]]
name="b"
path="src/b.rs"

[[bin]]
name="d"
path="src/d.rs"
