[package]
name = "16_1a"
version = "0.1.0"
authors = ["Keigo Oka <ogiekako@gmail.com>"]

[dependencies]
contest = { path = "../../../contest" }
petgraph = "0.4.1"

[[bin]]
name="a"
path="src/a.rs"

[[bin]]
name="b"
path="src/b.rs"

[[bin]]
name="c"
path="src/c.rs"
